
GET http://localhost:3000/subscribers/5e46cbba64d5452e777664b2
###
GET http://localhost:3000/subscribers

### 

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "",
  "subscribedChannel": "Bennetts Channel"
}

###

DELETE http://localhost:3000/subscribers/5e46cbba64d5452e777664b2

###

PATCH http://localhost:3000/subscribers/5e46c6951bfa472cb5af0e5a
Content-Type: application/json 

{
  "name": "John"
}